### ISSUE TITLE
trimModelList doesn't like fixed files

### ISSUE THREAD

**Issue by durack1** [PCMDI/climlib#2]
@pochedls I hit this error today:
```
import glob,os
from wrangle import trimModelList
path = '/p/user_pub/xclim/CMIP6/fx/sftlf'
fileList = glob.glob(os.path.join(path,'*.xml')); fileList.sort()
tmp = trimModelList(fileList); tmp.sort()
Traceback (most recent call last):
  File "<ipython-input-14-c9b9f7e0453b>", line 1, in <module>
    tmp = trimModelList(fileList); tmp.sort()
  File "/export/durack1/git/climlib/climlib/wrangle.py", line 129, in trimModelList
    cdate, publish, tpoints = getFileMeta(fn)
  File "/export/durack1/git/climlib/climlib/wrangle.py", line 93, in getFileMeta
    tpoints = len(fh['time'])
TypeError: object of type 'NoneType' has no len()
```
Problem is, the `fx` files have no `time` dimension:
```
import cdms2 as cdm
fH = cdm.open(fileList[0])
fH.directory
'/p/css03/esgf_publish/CMIP6/CFMIP/MIROC/MIROC6/abrupt-0p5xCO2/r1i1p1f1/fx/sftlf/gn/v20190705/'

(cdat82MesaPy3) bash-4.2$ ncdump -h /p/css03/esgf_publish/CMIP6/CFMIP/MIROC/MIROC6/abrupt-0p5xCO2/r1i1p1f1/fx/sftlf/gn/v20190705/sftlf_fx_MIROC6_abrupt-0p5xCO2_r1i1p1f1_gn.nc 
netcdf sftlf_fx_MIROC6_abrupt-0p5xCO2_r1i1p1f1_gn {
dimensions:
        lat = 128 ;
        lon = 256 ;
        bnds = 2 ;
        strlen = 4 ;
variables:
        double lat(lat) ;
...
        double lat_bnds(lat, bnds) ;
        double lon(lon) ;
...
        double lon_bnds(lon, bnds) ;
        char type(strlen) ;
                type:long_name = "Land area type" ;
                type:standard_name = "area_type" ;
        float sftlf(lat, lon) ;
...
                sftlf:units = "%" ;
...

// global attributes:
                :Conventions = "CF-1.7 CMIP-6.2" ;
                :activity_id = "CFMIP" ;
...
                :institution = "JAMSTEC (Japan Agency for Marine-Earth Science and Technology, Kanagawa 236-0001, Japan), AORI (Atmosphere and Ocean Research Institute, The University of Tokyo, Chiba 277-8564, Japan), NIES (National Institute for Environmental Studies, Ibaraki 305-8506, Japan), and R-CCS (RIKEN Center for Computational Science, Hyogo 650-0047, Japan)" ;
                :institution_id = "MIROC" ;
                :mip_era = "CMIP6" ;
...
                :cmor_version = "3.4.0" ;
}
```

**Comment by durack1** [comment]
@pochedls looks like we need an `if` statement in [climlib/wrangle.py:getFileMeta](https://github.com/PCMDI/climlib/blob/master/climlib/wrangle.py#L93)

**Comment by durack1** [comment]
@pochedls works like a charm! thanks
