### ISSUE TITLE
pyesgf new (non-CDAT env) dependable

### ISSUE THREAD

**Issue by durack1** [PCMDI/climlib#8]
This error is a motivator for me to pull climlib into a conda env, so dependencies can be resolved
```python
(cdat821nompi) bash-4.2$ python makeRothigData.py 
Traceback (most recent call last):
  File "makeRothigData.py", line 25, in <module>
    from wrangle import trimModelList ; # climlib
  File "~git/climlib/climlib/wrangle.py", line 19, in <module>
    from pyesgf.search import SearchConnection
ModuleNotFoundError: No module named 'pyesgf'
```

**Comment by durack1** [comment]
@pochedls I assume there are no conflicts with `pyesgf` and cdat821?

**Comment by pochedls** [comment]
@durack1 - what if I just eliminate all of this functionality and the pyesgf dependency?

**Comment by durack1** [comment]
I wonder if there is a graceful way to load a module if it's available and turn it off if not. I think it's silly to remove useful functions, so let me sit on this for a think
